// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/18/2025, 10:13:32 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/Users/tayloralphaaa/portfolio-v3-master/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/tayloralphaaa/portfolio-v3-master/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/tayloralphaaa/portfolio-v3-master/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/tayloralphaaa/portfolio-v3-master/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/tayloralphaaa/portfolio-v3-master/plugins/**/*.{js,ts,mjs}","/Users/tayloralphaaa/portfolio-v3-master/composables/**/*.{js,ts,mjs}","/Users/tayloralphaaa/portfolio-v3-master/utils/**/*.{js,ts,mjs}","/Users/tayloralphaaa/portfolio-v3-master/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/tayloralphaaa/portfolio-v3-master/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/tayloralphaaa/portfolio-v3-master/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/tayloralphaaa/portfolio-v3-master/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;