// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/12/2025, 11:12:24 PM
const configMerger = require("/Users/tayloralphaaa/portfolio-v3-master/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [

].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["/Users/tayloralphaaa/portfolio-v3-master/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/tayloralphaaa/portfolio-v3-master/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/tayloralphaaa/portfolio-v3-master/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/tayloralphaaa/portfolio-v3-master/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/tayloralphaaa/portfolio-v3-master/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/tayloralphaaa/portfolio-v3-master/plugins/**/*.{js,ts,mjs}","/Users/tayloralphaaa/portfolio-v3-master/composables/**/*.{js,ts,mjs}","/Users/tayloralphaaa/portfolio-v3-master/utils/**/*.{js,ts,mjs}","/Users/tayloralphaaa/portfolio-v3-master/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/tayloralphaaa/portfolio-v3-master/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/tayloralphaaa/portfolio-v3-master/app.config.{js,ts,mjs}"] } }));

module.exports = config
