<<<<<<< HEAD
// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 8/31/2025, 6:44:29 AM
const configMerger = require("/Users/tayloralphaaa/portfolio-v3-master-main/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");
=======
// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 1/11/2025, 1:23:18 PM
const configMerger = require("/Users/taylorbuildzz/portfolio-v3-master/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");
>>>>>>> 6e8ec1e3102f642078bf0e8d3595bdb2b6d6cc4f

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [

<<<<<<< HEAD
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["/Users/tayloralphaaa/portfolio-v3-master-main/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/tayloralphaaa/portfolio-v3-master-main/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/tayloralphaaa/portfolio-v3-master-main/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/tayloralphaaa/portfolio-v3-master-main/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/tayloralphaaa/portfolio-v3-master-main/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/tayloralphaaa/portfolio-v3-master-main/plugins/**/*.{js,ts,mjs}","/Users/tayloralphaaa/portfolio-v3-master-main/composables/**/*.{js,ts,mjs}","/Users/tayloralphaaa/portfolio-v3-master-main/utils/**/*.{js,ts,mjs}","/Users/tayloralphaaa/portfolio-v3-master-main/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/tayloralphaaa/portfolio-v3-master-main/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/tayloralphaaa/portfolio-v3-master-main/app.config.{js,ts,mjs}"] } }));
=======
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["/Users/taylorbuildzz/portfolio-v3-master/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/taylorbuildzz/portfolio-v3-master/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/taylorbuildzz/portfolio-v3-master/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/taylorbuildzz/portfolio-v3-master/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/taylorbuildzz/portfolio-v3-master/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/taylorbuildzz/portfolio-v3-master/plugins/**/*.{js,ts,mjs}","/Users/taylorbuildzz/portfolio-v3-master/composables/**/*.{js,ts,mjs}","/Users/taylorbuildzz/portfolio-v3-master/utils/**/*.{js,ts,mjs}","/Users/taylorbuildzz/portfolio-v3-master/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/taylorbuildzz/portfolio-v3-master/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/taylorbuildzz/portfolio-v3-master/app.config.{js,ts,mjs}"] } }));
>>>>>>> 6e8ec1e3102f642078bf0e8d3595bdb2b6d6cc4f

module.exports = config
